CREATE TABLE [dbo].[Roles]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(255) NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_Roles_Name ON [dbo].[Roles]([Name]);
GO
